from typing import Dict

CITY_SYNONYMS: Dict[str, str] = {
    "bangalore": "bengaluru",
    "blr": "bengaluru",
    "bengaluru": "bengaluru",
    "bombay": "mumbai",
    "bombai": "mumbai",
    "delhi": "new delhi",
    "newdelhi": "new delhi",
    "gurgaon": "gurugram",
    "ggn": "gurugram",
    "gurugram": "gurugram",
    "calcutta": "kolkata",
    "kolkotta": "kolkata",
    "chennai": "chennai",
    "madras": "chennai",
    "hyderabad": "hyderabad",
    "hyd": "hyderabad",
    "poona": "pune",
    "pune": "pune",
    "ahmedabad": "ahmedabad",
    "amdavad": "ahmedabad",
    "ahmdabad": "ahmedabad",
    "jaipur": "jaipur",
    "jpr": "jaipur",
    "kanpur": "kanpur",
    "cawnpore": "kanpur",
    "nagpur": "nagpur",
    "npr": "nagpur",
    "lucknow": "lucknow",
    "lko": "lucknow",
    "vadodara": "vadodara",
    "baroda": "vadodara",
    "surat": "surat",
    "srt": "surat",
    "indore": "indore",
    "ind": "indore",
    "thane": "thane",
    "thana": "thane",
    "bhopal": "bhopal",
    "bhopal": "bhopal",
    "patna": "patna",
    "patna": "patna",
    "visakhapatnam": "visakhapatnam",
    "vizag": "visakhapatnam",
    "vskp": "visakhapatnam",
    "agra": "agra",
    "agartala": "agartala",
    "coimbatore": "coimbatore",
    "cbe": "coimbatore",
    "amritsar": "amritsar",
    "asr": "amritsar",
    "allahabad": "prayagraj",
    "prayagraj": "prayagraj",
    "varanasi": "varanasi",
    "banaras": "varanasi",
    "bareilly": "bareilly",
    "bareli": "bareilly",
    "jabalpur": "jabalpur",
    "jubbulpore": "jabalpur",
    "gwalior": "gwalior",
    "gwalior": "gwalior",
    "ranchi": "ranchi",
    "rnch": "ranchi",
    "rajkot": "rajkot",
    "rajkot": "rajkot",
    "kochi": "kochi",
    "cochin": "kochi",
    "ghaziabad": "ghaziabad",
    "gaziabad": "ghaziabad",
    "ludhiana": "ludhiana",
    "ldh": "ludhiana",
    "jaipur": "jaipur",
    "jpr": "jaipur",
    "aurangabad": "aurangabad",
    "sambhajinagar": "aurangabad",
    "bhubaneswar": "bhubaneswar",
    "bbsr": "bhubaneswar",
    "thiruvananthapuram": "thiruvananthapuram",
    "trivandrum": "thiruvananthapuram",
    "mysuru": "mysuru",
    "mysore": "mysuru",
    "chandigarh": "chandigarh",
    "chd": "chandigarh",
    "faridabad": "faridabad",
    "frbd": "faridabad",
    "noida": "noida",
    "greater noida": "noida",
    "goa": "goa",
    "panaji": "goa",
    "nagaland": "nagaland",
    "kohima": "nagaland",
    "srinagar": "srinagar",
    "srn": "srinagar",
    "jamshedpur": "jamshedpur",
    "jsr": "jamshedpur",
    "kota": "kota",
    "kt": "kota",
    "guwahati": "guwahati",
    "ghy": "guwahati",
    "haridwar": "haridwar",
    "hwr": "haridwar",
    "dehradun": "dehradun",
    "ddn": "dehradun",
    "shimla": "shimla",
    "shm": "shimla",
    "puducherry": "puducherry",
    "pondicherry": "puducherry",
    "tiru": "tiruchirappalli",
    "trichy": "tiruchirappalli",
    "tirupur": "tiruppur",
    "tirupur": "tiruppur",
    "salem": "salem",
    "slm": "salem",
    "guntur": "guntur",
    "gnt": "guntur",
    "vijayawada": "vijayawada",
    "vja": "vijayawada",
    "hubballi": "hubli",
    "hubli": "hubli",
    "dharwad": "dharwad",
    "hubli-dharwad": "hubli",
    "jodhpur": "jodhpur",
    "jdh": "jodhpur",
    "aligarh": "aligarh",
    "aligarh": "aligarh",
    "meerut": "meerut",
    "mrt": "meerut",
    "jamnagar": "jamnagar",
    "jmn": "jamnagar",
    "nanded": "nanded",
    "ndd": "nanded",
    "kolhapur": "kolhapur",
    "klp": "kolhapur",
    "nashik": "nashik",
    "nasik": "nashik",
    "solapur": "solapur",
    "slr": "solapur",
    "bikaner": "bikaner",
    "bkn": "bikaner",
    "ajmer": "ajmer",
    "ajmer": "ajmer",
    "udaipur": "udaipur",
    "udpr": "udaipur",
    "bhavnagar": "bhavnagar",
    "bvn": "bhavnagar",
    "mangalore": "mangaluru",
    "mangaluru": "mangaluru",
    "rohtak": "rohtak",
    "rtk": "rohtak",
    "hisar": "hisar",
    "hsr": "hisar",
    "jhansi": "jhansi",
    "jhs": "jhansi",
    "muzaffarnagar": "muzaffarnagar",
    "mzn": "muzaffarnagar",
    "saharanpur": "saharanpur",
    "sre": "saharanpur",
    "moradabad": "moradabad",
    "mbd": "moradabad",
    "firozabad": "firozabad",
    "fbd": "firozabad",
    "rampur": "rampur",
    "rmpur": "rampur",
    "muzaffarpur": "muzaffarpur",
    "mzp": "muzaffarpur",
    "bhagalpur": "bhagalpur",
    "bgp": "bhagalpur",
    "durgapur": "durgapur",
    "dur": "durgapur",
    "asansol": "asansol",
    "asn": "asansol",
    "dhanbad": "dhanbad",
    "dhb": "dhanbad",
    "kakinada": "kakinada",
    "kkd": "kakinada",
    "nellore": "nellore",
    "nlr": "nellore",
    "rajahmundry": "rajahmundry",
    "rjym": "rajahmundry",
    "tirupati": "tirupati",
    "tpty": "tirupati",
    "kozhikode": "kozhikode",
    "calicut": "kozhikode",
    "thrissur": "thrissur",
    "trichur": "thrissur",
    "sagar": "sagar",
    "sgr": "sagar",
    "ujjain": "ujjain",
    "ujn": "ujjain",
    "ambala": "ambala",
    "umb": "ambala",
    "panipat": "panipat",
    "pnp": "panipat",
    "kurukshetra": "kurukshetra",
    "kkr": "kurukshetra",
    "jalandhar": "jalandhar",
    "juc": "jalandhar",
    "patiala": "patiala",
    "pta": "patiala",
    "gandhinagar": "gandhinagar",
    "gandhi nagar": "gandhinagar",
    "bhavnagar": "bhavnagar",
    "bvn": "bhavnagar",
    "jammu": "jammu",
    "jmu": "jammu",
    "tinsukia": "tinsukia",
    "tski": "tinsukia",
    "siliguri": "siliguri",
    "sgu": "siliguri",
    "howrah": "howrah",
    "hwh": "howrah",
    "bhilai": "bhilai",
    "bhi": "bhilai",
    "raipur": "raipur",
    "rpr": "raipur",
    "kharagpur": "kharagpur",
    "kgp": "kharagpur",
    "palakkad": "palakkad",
    "palghat": "palakkad",
    "kanchipuram": "kanchipuram",
    "kanjeevaram": "kanchipuram",
    "madurai": "madurai",
    "madurai": "madurai",
    "puducherry": "puducherry",
    "pondicherry": "puducherry",
    "rajahmundry": "rajahmundry",
    "rajmundry": "rajahmundry",
    "tirupati": "tirupati",
    "tpt": "tirupati",
    "warangal": "warangal",
    "warangal": "warangal",
    "bikaner": "bikaner",
    "bkn": "bikaner",
    "kota": "kota",
    "kt": "kota",
    "udaipur": "udaipur",
    "udpr": "udaipur",
    "salem": "salem",
    "slm": "salem",
    "vijayawada": "vijayawada",
    "vja": "vijayawada",
    "hubli": "hubli",
    "hubli-dharwad": "hubli",
    "jodhpur": "jodhpur",
    "jdh": "jodhpur",
    "meerut": "meerut",
    "mrt": "meerut",
    "vasai-virar": "vasai-virar",
    "vasai virar": "vasai-virar",
    "pimpri-chinchwad": "pimpri-chinchwad",
    "pimpri chinchwad": "pimpri-chinchwad",
}


AREA_SYNONYMS: Dict[str, str] = {
    # Bengaluru
    "kormangala": "koramangala",
    "koromangala": "koramangala",
    "hsrlayout": "hsr layout",
    "hsr": "hsr layout",
    "indiragar": "indiranagar",
    "in": "indiranagar",
    "ejipura": "ejipura",
    "domlur": "domlur",
    "jp nagar": "j p nagar",
    "jayanagar": "jayanagar",
    "whitefield": "whitefield",
    "ecity": "electronic city",
    "marathahalli": "marathahalli",
    "bellandur": "bellandur",
    "kr puram": "krishnarajapuram",
    "krishnarajapuram": "krishnarajapuram",
    "malleshwaram": "malleshwaram",
    "hebbal": "hebbal",
    "yelahanka": "yelahanka",
    "sarjapur": "sarjapur road",
    "sarjapura": "sarjapur road",
    "jalahalli": "jalahalli",

    # Mumbai
    "andheri east": "andheri",
    "andheri west": "andheri",
    "bandra": "bandra",
    "bkc": "bandra kurla complex",
    "powai": "powai",
    "borivali": "borivali",
    "malad": "malad",
    "chembur": "chembur",
    "ghatkopar": "ghatkopar",
    "dadar": "dadar",
    "worli": "worli",
    "colaba": "colaba",
    "goregaon": "goregaon",
    "panvel": "panvel",
    "kharghar": "kharghar",
    "vashi": "vashi",
    "thane west": "thane",
    "thane east": "thane",
    "mulund": "mulund",
    "sion": "sion",
    "churchgate": "churchgate",
    "nariman point": "nariman point",
    "andheri": "andheri",

    # Delhi
    "dwarka": "dwarka",
    "rohini": "rohini",
    "lajpat nagar": "lajpat nagar",
    "hauz khas": "hauz khas",
    "saket": "saket",
    "cp": "connaught place",
    "paharganj": "paharganj",
    "chandni chowk": "chandni chowk",
    "karol bagh": "karol bagh",
    "vikaspuri": "vikaspuri",
    "laxmi nagar": "laxmi nagar",
    "mayur vihar": "mayur vihar",
    "pitampura": "pitampura",
    "shahdara": "shahdara",
    "janakpuri": "janakpuri",
    "tilak nagar": "tilak nagar",
    "vns": "vasant kunj",
    "vasant kunj": "vasant kunj",
    "gk": "greater kailash",
    "greater kailash": "greater kailash",

    # Chennai
    "anna nagar": "anna nagar",
    "t nagar": "t nagar",
    "adyar": "adyar",
    "velachery": "velachery",
    "mylapore": "mylapore",
    "tambaram": "tambaram",
    "porur": "porur",
    "sholinganallur": "sholinganallur",
    "nungambakkam": "nungambakkam",
    "thiruvanmiyur": "thiruvanmiyur",
    "omr": "omr",
    "guindy": "guindy",
    "chengalpattu": "chengalpattu",
    "ambattur": "ambattur",
    "adyar": "adyar",
    "pallavaram": "pallavaram",
    "pammal": "pammal",
    "medavakkam": "medavakkam",
    "vadapalani": "vadapalani",
    "tiruvottiyur": "tiruvottiyur",

    # Kolkata
    "salt lake": "salt lake city",
    "bengaluru": "kolkata",
    "saltlake": "salt lake city",
    "sector v": "salt lake city",
    "new town": "new town",
    "newtown": "new town",
    "rajarhat": "rajarhat",
    "esplanade": "esplanade",
    "park street": "park street",
    "howrah": "howrah",
    "barrackpore": "barrackpore",
    "dum dum": "dum dum",
    "dumdum": "dum dum",
    "gariahat": "gariahat",
    "garia": "garia",
    "tollygunge": "tollygunge",
    "behala": "behala",
    "jadavpur": "jadavpur",
    "sodepur": "sodepur",
    "dunlop": "dunlop",
    "agarpara": "agarpara",

    # Pune
    "koregaon park": "koregaon park",
    "koregaon": "koregaon park",
    "viman nagar": "viman nagar",
    "vimannagar": "viman nagar",
    "hinjewadi": "hinjawadi",
    "hinjawadi": "hinjawadi",
    "baner": "baner",
    "kharadi": "kharadi",
    "aundh": "aundh",
    "pimple saudagar": "pimple saudagar",
    "pimpri": "pimpri",
    "chinchwad": "chinchwad",
    "magarpatta": "magarpatta city",
    "magarpatta city": "magarpatta city",
    "fc road": "fergusson college road",
    "jm road": "j m road",
    "wakad": "wakad",
    "moshi": "moshi",
    "aundh": "aundh",
    "shivaji nagar": "shivaji nagar",
    "katraj": "katraj",
    "hadapsar": "hadapsar",

    # Ahmedabad
    "sg highway": "sg highway",
    "sg road": "sg highway",
    "satellite": "satellite",
    "vastrapur": "vastrapur",
    "bodakdev": "bodakdev",
    "maninagar": "maninagar",
    "chandkheda": "chandkheda",
    "bopal": "bopal",
    "ghatlodia": "ghatlodia",
    "paldi": "paldi",
    "thaltaj": "thaltej",
    "thaltej": "thaltej",
    "navrangpura": "navrangpura",
    "usmanpura": "usmanpura",
    "gandhinagar": "gandhinagar",
    "gandhinagar": "gandhinagar",
    "iskon": "iskon cross roads",
    "iskcon": "iskon cross roads",
    "motera": "motera",

    # Hyderabad
    "gachibowli": "gachibowli",
    "gachi bowli": "gachibowli",
    "kondapur": "kondapur",
    "hi tech city": "hitec city",
    "hitech city": "hitec city",
    "jubilee hills": "jubilee hills",
    "jhills": "jubilee hills",
    "b anghills": "banjara hills",
    "banjara hills": "banjara hills",
    "ameerpet": "ameerpet",
    "lingampally": "lingampally",
    "lb nagar": "l b nagar",
    "lb nagar": "l b nagar",
    "kukatpally": "kukatpally",
    "madhapur": "madhapur",
    "secunderabad": "secunderabad",
    "sindhi colony": "secunderabad",
    "miyapur": "miyapur",
    "hitec city": "hitec city",
    "panjagutta": "panjagutta",
    "attapur": "attapur",
    "shamshabad": "shamshabad",
    "shamshabad": "shamshabad",

    # Others (Selected examples for other common cities)
    "noida": "noida",
    "greater noida": "greater noida",
    "sector 62": "noida sector 62",
    "sector 18": "noida sector 18",
    "cyber hub": "cyber city",
    "cyber city": "cyber city",
    "sector 29": "sector 29",
    "vellore": "vellore",
    "vit": "vellore",
    "pondicherry": "puducherry",
    "puducherry": "puducherry",
    "varkala": "varkala",
    "kovalam": "kovalam",
    "thekkady": "thekkady",
    "mundakayam": "mundakayam",
    "coorg": "coorg",
    "chikmagalur": "chikmagalur",
    "gokarna": "gokarna",
    "hampi": "hampi",
    "varanasi": "varanasi",
    "kashi": "varanasi",
    "pragyaraj": "prayagraj",
    "allahabad": "prayagraj",
    "bhopal": "bhopal",
    "hoshangabad": "bhopal",
    "ujjain": "ujjain",
    "mahakaal": "ujjain",
    "ajmer": "ajmer",
    "pushkar": "ajmer",
    "sri ganganagar": "sriganganagar",
    "kota": "kota",
    "jodhpur": "jodhpur",
    "jaisalmer": "jaisalmer",
    "jaipur": "jaipur",
    "ambala cantt": "ambala",
    "ambala cantt": "ambala",
    "patiala": "patiala",
    "amritsar": "amritsar",
    "jalandhar": "jalandhar",
    "ludhiana": "ludhiana",
    "rohtak": "rohtak",
    "kurukshetra": "kurukshetra",
    "panipat": "panipat",
    "sonepat": "sonepat",
    "hisar": "hisar",
    "bhubaneshwar": "bhubaneswar",
    "bbsr": "bhubaneswar",
    "puri": "puri",
    "konark": "konark",
}